services:
  postgres:
    image: 'postgres:16'
    container_name: 'purchase-container'
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: purchase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: