spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mypass
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml


server:
  error:
    include-message: always
    include-binding-errors: always