-- добавление новых столбцов
alter table customer
    add column new_customer_code bigint generated by default as identity;

alter table lot
    add column new_lot_id bigint generated by default as identity;

-- копирование данных в новые столбцы
update customer
set new_customer_code = customer_code;

update lot
set new_lot_id = lot_id;

-- удаление старых столбцов и ограничений
alter table lot
    drop constraint lot_customer_code_fkey;

alter table customer
    drop column customer_code;

alter table lot
    drop column lot_id;

-- переименование временных столбцов
alter table customer
    rename column new_customer_code to customer_code;

alter table lot
    rename column new_lot_id to lot_id;

-- переустановка ограничений
alter table customer
    add primary key (customer_code);

alter table lot add constraint lot_customer_code_fkey
    foreign key (customer_code) references customer (customer_code) on delete set null;

alter table lot add primary key (lot_id);